### ISSUE TITLE
Exportfunktion Homematic und/oder iobroker

### ISSUE THREAD

**Issue by Dax88** [tirolerstefan/kaifa#7] opened 2021-11-30 07:28 UTC
Wäre es möglich eine Export-Funktion für Homematic oder ioBroker einzubauen?

**Comment by tirolerstefan** [comment] 2021-11-30 20:50
How should this export look like?

**Comment by boredomwontgetus** [comment] 2021-11-30 21:47
May i kindly suggest a more open/generic export implementation like MQTT?

**Comment by Dax88** [comment] 2021-12-01 06:15
MQTT sounds great!

**Comment by tirolerstefan** [comment] 2021-12-01 20:06
Feel free to give an example or add an example implementation as pull request for a better overview.

**Comment by boredomwontgetus** [comment] 2021-12-01 20:49
yeah, once i get my meter i will give it a shot and file a PR.

**Comment by tirolerstefan** [comment] 2022-01-19 18:11
this will be done in issue #9 / #12

**Comment by tirolerstefan** [comment] 2022-01-19 18:13
Duplicate of #9

**Closed by tirolerstefan** 2022-01-19 18:13 UTC
Labels: enhancement
